name: Run Tests

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Set environment variables
      run: |
        echo "DATABASE_URL=postgresql://test_user:test_pass@localhost:5432/test_db" >> $GITHUB_ENV
        echo "SECRET_KEY=test-secret-key-for-testing-only" >> $GITHUB_ENV
        echo "FLASK_ENV=testing" >> $GITHUB_ENV

    - name: Run unit tests
      run: |
        python test_assessment_math.py

    - name: Run team dashboard tests
      run: |
        python test_team_dashboard.py

    - name: Check code quality (optional)
      run: |
        pip install flake8
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
      continue-on-error: true

    - name: Test summary
      if: always()
      run: |
        echo "✅ Tests completed"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
